# Generated by Django 3.1 on 2020-08-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealityWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetPriceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('category', models.CharField(choices=[('domek', 'domek'), ('mieszkanie', 'mieszkanie')], max_length=20)),
                ('subject', models.CharField(max_length=120)),
            ],
        ),
    ]
