# Generated by Django 3.1.1 on 2020-09-16 13:30

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RealityWeb', '0002_getpricemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='FindFeaturesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=4, max_digits=7)),
                ('lon', models.DecimalField(decimal_places=4, max_digits=7)),
                ('mapka_radius', models.IntegerField()),
                ('city', models.CharField(max_length=40)),
                ('feature_shop', multiselectfield.db.fields.MultiSelectField(choices=[('all_shop', 'WSZYSTKIE'), ('mall', 'centrum handlowe'), ('pastry', 'cukiernia'), ('department_store', 'dom towarowy'), ('chemist', 'drogeria'), ('hairdresser', 'fryzjer'), ('deli', 'garmażeria'), ('kiosk', 'kiosk'), ('florist', 'kwiaciarnia'), ('ice_cream', 'lodziarnia'), ('bakery', 'piekarnia'), ('butcher', 'rzeźnik'), ('beauty', 'salon piękności'), ('jewelry', 'sklep jubilerski'), ('alcohol', 'sklep monopolowy'), ('convenience', 'sklep wielobranzowy'), ('coffee', 'sklep z kawa'), ('beverages', 'sklep z napojami'), ('seafood', 'sklep z owocami morza'), ('wine', 'sklep z winami'), ('confectionery', 'sklep cukierniczy'), ('art', 'sklep ze sztuka'), ('supermarket', 'supermarket'), ('greengrocer', 'warzywniak'), ('none_shop', 'ZADNE')], default=('all_shop', 'WSZYSTKIE'), max_length=800)),
                ('feature_amenity_fun', multiselectfield.db.fields.MultiSelectField(choices=[('all_fun', 'WSZYSTKIE'), ('vending_machine', 'automat vendingowy'), ('bank', 'bank'), ('atm', 'bankomat'), ('bar', 'bar'), ('fast_food', 'fast food'), ('arts_centre', 'galeria sztuki'), ('cafe', 'kawiarnia'), ('cinema', 'kino'), ('nightclub', 'klub nocny'), ('post_office', 'poczta'), ('police', 'policja'), ('pub', 'pub'), ('restaurant', 'restauracja'), ('theatre', 'teatr'), ('bicycle_rental', 'wypozyczalnia rowerow'), ('none_fun', 'ZADNE')], default=('all_fun', 'WSZYSTKIE'), max_length=800)),
                ('feature_amenity_healthcare', multiselectfield.db.fields.MultiSelectField(choices=[('all_helthcare', 'WSZYSTKIE'), ('pharmacy', 'apteka'), ('dentist', 'dentysta'), ('doctors', 'gabinet lekarski'), ('clinic', 'klinika'), ('hospital', 'szpital'), ('none_helthcare', 'ZADNE')], default=('all_helthcare', 'WSZYSTKIE'), max_length=800)),
                ('feature_amenity_schooling', multiselectfield.db.fields.MultiSelectField(choices=[('all_schooling', 'WSZYSTKIE'), ('library', 'biblioteka'), ('kindergarten', 'przedszkole'), ('school', 'szkola'), ('college', 'uczelnia'), ('university', 'uniwersytet'), ('none_schooling', 'ZADNE')], default=('all_schooling', 'WSZYSTKIE'), max_length=800)),
                ('feature_leisure', multiselectfield.db.fields.MultiSelectField(choices=[('all_leisure', 'WSZYSTKIE'), ('fitness_centre', 'centrum fitness'), ('sports_centre', 'ośrodek sportowy'), ('park', 'park'), ('playground', 'plac zabaw'), ('nature_reserve', 'rezerwat przyrody'), ('none_leisure', 'ZADNE')], default=('all_leisure', 'WSZYSTKIE'), max_length=800)),
                ('feature_transport', multiselectfield.db.fields.MultiSelectField(choices=[('all_transport', 'WSZYSTKIE'), ('bus', 'przystanek autobusowy'), ('subway', 'metro'), ('train', 'przystanek kolejowy'), ('stop_position', 'przystanek'), ('tram', 'przystanek tramwajowy'), ('none_transport', 'ZADNE')], default=('all_transport', 'WSZYSTKIE'), max_length=800)),
                ('feature_tourism', multiselectfield.db.fields.MultiSelectField(choices=[('all_tourism', 'WSZYSTKIE'), ('attraction', 'atrakcje'), ('artwork', 'dzieła sztuki'), ('hotel', 'hotel'), ('museum', 'muzeum'), ('viewpoint', 'punkt widokowy'), ('none_tourism', 'ZADNE')], default=('all_tourism', 'WSZYSTKIE'), max_length=800)),
            ],
        ),
        migrations.AlterField(
            model_name='getpricemodel',
            name='tagi',
            field=models.CharField(max_length=200),
        ),
    ]
