# Generated by Django 3.1.1 on 2020-09-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealityWeb', '0003_auto_20200916_1330'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
