# Generated by Django 3.1.1 on 2020-09-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealityWeb', '0004_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getpricemodel',
            name='tagi',
            field=models.CharField(max_length=2000),
        ),
    ]
