version: "3.7"

x-service-volumes: &service-volumes
    - ./:/app/:rw,cached

x-database-variables: &database-variables
    POSTGRES_DB: RealityWeb
    POSTGRES_USER: realityadmin
    POSTGRES_PASSWORD: Reality1!

x-app-variables: &app-variables
    <<: *database-variables
    POSTGRES_HOST: postgres

services:
    website:
        image: realityweb:latest
        command: python manage.py runserver 0.0.0.0:8000
        volumes: *service-volumes
        depends_on: 
            - db_migrate
        ports:
            - "8000:8000"
        networks:
            - main_network

    db_migrate:
        image: realityweb:latest
        command: python manage.py migrate
        volumes: *service-volumes
        environment: *app-variables
        depends_on: 
            - postgres
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        networks:
            - main_network


    postgres:
        image: kartoza/postgis:12.0
        restart: always
        environment:
            POSTGRES_USER: realityadmin
            POSTGRES_PASSWORD: Reality1!
            POSTGRES_DB: realestate_zero,RealityWeb
            POSTGRES_MULTIPLE_EXTENSIONS: postgis
        ports: 
            - "5431:5432"
        volumes:
            - ./nowa.sql:/docker-entrypoint-initdb.d/nowa.sql
            - db-data:/var/lib/postgresql/data
        networks:
            - main_network
        # command: bash -c "psql -U realityadmin [--password Reality1!] -a -f realestate_zero.sql"


    pgadmin:
        image: dpage/pgadmin4:4.20
        depends_on:
            - postgres
        ports:
            - "5555:80"
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
            PGADMIN_DEFAULT_PASSWORD: admin
        restart: unless-stopped
        networks:
            - main_network
            
    # redis:
    #     image: redis:4
    #     ports: 
    #         - "6379:6379"

volumes:
    db-data:

networks:
    main_network: